language: rust
sudo: false

matrix:
  include:

  # tests pass
  - rust: stable
    script:
    - cargo test --all --locked
    - rustup component add rustfmt-preview
    - cargo fmt -- --write-mode=diff
